// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using signinapi.Models;

#nullable disable

namespace signupapi.Migrations.Signin
{
    [DbContext(typeof(SigninContext))]
    [Migration("20230623083855_InitialMigrationSignin")]
    partial class InitialMigrationSignin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("signinapi.Models.Signin", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.HasKey("Username");

                    b.ToTable("Signins");
                });
#pragma warning restore 612, 618
        }
    }
}
